version: '2'
networks:
  front:
    external:
      name: nginxproxy_frontend
  back:
    driver: bridge

#volumes:
#  apps:
#    driver: local-persist
#    driver_opts:
#      mountpoint: "./data/apps"
#  config:
#    driver: local-persist
#    driver_opts:
#      mountpoint: "./data/config"
#  data:
#    driver: local-persist
#    driver_opts:
#      mountpoint: "./data/data"
#  mysql:
#    driver: local-persist
#    driver_opts:
#      mountpoint: "./data/mysql"
#volumes:
#    nextcloud:

services:
    #  web:
    #    image: nginx
    #    container_name: nextcloud-web
    #    environment:
    #      - VIRTUAL_HOST=cloud.k0v1.xyz
    #      - LETSENCRYPT_HOST=cloud.k0v1.xyz
    #      - LETSENCRYPT_EMAIL=foo@bar.com
    #    volumes:
    #      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #      - nextcloud:/var/www/html
    #      - ./data/apps:/var/www/html/apps
    #      - ./data/config:/var/www/html/config
    #      - ./data/data:/var/www/html/data
    #    links:
    #      - app
    #      - db
    #    networks:
    #      - back
    #      - front
  app:
    image: nextcloud #:11-fpm
    container_name: nextcloud-app
    environment:
      - VIRTUAL_HOST=cloud.k0v1.xyz
      - LETSENCRYPT_HOST=cloud.k0v1.xyz
      - LETSENCRYPT_EMAIL=foo@bar.com
    links:
      - db
    volumes:
      - ./data/apps:/var/www/html/apps
      - ./data/config:/var/www/html/config
      - ./data/data:/var/www/html/data
    networks:
      - back
      - front 
  db:
    image: mysql
    container_name: nextcloud-db
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
      - back
  cron:
    image: nextcloud #:11-fpm
    container_name: nextcloud-cron
    volumes_from:
      - app
    links:
      - db
    user: www-data
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        sleep 900
        /usr/local/bin/php /var/www/html/cron.php
      done
      EOF'
    networks:
      - back
